# Generated by Django 4.0.5 on 2022-07-28 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_table',
            name='room_key',
            field=models.BigIntegerField(default='4438', unique=True),
        ),
    ]
