# Generated by Django 4.0.5 on 2022-07-28 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0002_alter_booking_table_room_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_table',
            name='room_key',
            field=models.IntegerField(max_length=4),
        ),
    ]
