# Generated by Django 4.0.5 on 2022-07-28 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0003_alter_booking_table_room_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='check_out_table',
            name='booking',
        ),
    ]
