# Generated by Django 4.0.5 on 2022-07-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0004_remove_check_out_table_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking_table',
            old_name='check_in',
            new_name='potential_check_in',
        ),
        migrations.RenameField(
            model_name='booking_table',
            old_name='check_out',
            new_name='potential_check_out',
        ),
        migrations.RenameField(
            model_name='check_out_table',
            old_name='check_in',
            new_name='real_check_in',
        ),
        migrations.RenameField(
            model_name='check_out_table',
            old_name='check_out',
            new_name='real_check_out',
        ),
        migrations.AddField(
            model_name='booking_table',
            name='real_check_in',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='booking_table',
            name='real_check_out',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='booking_table',
            name='room_key',
            field=models.IntegerField(),
        ),
    ]
