# Generated by Django 4.0.5 on 2022-07-29 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0005_rename_check_in_booking_table_potential_check_in_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='check_out_table',
            old_name='check_id',
            new_name='check_out_id',
        ),
        migrations.RemoveField(
            model_name='check_out_table',
            name='user',
        ),
        migrations.CreateModel(
            name='Check_in_table',
            fields=[
                ('check_in_id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=15, null=True)),
                ('first_name', models.CharField(blank=True, max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('mail', models.EmailField(max_length=30, null=True)),
                ('real_check_in', models.DateField()),
                ('real_check_out', models.DateField(null=True)),
                ('number_of_adult', models.IntegerField(null=True)),
                ('number_of_children', models.IntegerField(null=True)),
                ('rooms', models.CharField(choices=[('Standard Room', 'Standard Room'), ('Double Standard Room', 'Double Standard Room'), ('Executive Rooms', 'Executive Rooms'), ('Deluxe Rooms', 'Deluxe Rooms'), ('Classic Suite', 'Classic Suite'), ('Presidential Suite', 'Presidential Suite')], max_length=60)),
                ('key', models.BigIntegerField(default=0)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookingapp.room_table')),
            ],
        ),
    ]
