# Generated by Django 4.0.5 on 2022-07-29 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0007_booking_table_check_in_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='check_in_table',
            old_name='real_check_in',
            new_name='potential_check_in',
        ),
        migrations.RenameField(
            model_name='check_in_table',
            old_name='real_check_out',
            new_name='potential_check_out',
        ),
    ]
