# Generated by Django 4.0.5 on 2022-07-29 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0008_rename_real_check_in_check_in_table_potential_check_in_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_table',
            name='room_key',
            field=models.BigIntegerField(),
        ),
    ]
