# Generated by Django 4.0.5 on 2022-07-29 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0010_rename_real_check_out_check_out_table_potential_check_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='check_out_table',
            name='check_in',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookingapp.check_in_table'),
        ),
    ]
