# Generated by Django 4.0.5 on 2022-07-29 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0011_check_out_table_check_in'),
    ]

    operations = [
        migrations.RenameField(
            model_name='check_out_table',
            old_name='check_in',
            new_name='check_me',
        ),
    ]
