# Generated by Django 4.0.5 on 2022-07-30 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0013_remove_check_out_table_check_me'),
    ]

    operations = [
        migrations.AddField(
            model_name='check_out_table',
            name='book_me',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookingapp.booking_table'),
        ),
    ]
