# Generated by Django 4.0.5 on 2022-07-30 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0014_check_out_table_book_me'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking_table',
            name='user',
        ),
    ]
