# Generated by Django 4.0.5 on 2022-07-30 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0015_remove_booking_table_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='room_table',
            name='room_price',
            field=models.IntegerField(default=0),
        ),
    ]
