# Generated by Django 4.0.5 on 2022-07-30 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0016_room_table_room_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room_table',
            name='room_price',
            field=models.BigIntegerField(default=0),
        ),
    ]
