# Generated by Django 4.0.5 on 2022-08-02 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0017_alter_room_table_room_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_table',
            name='room_price',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='booking_table',
            name='total_price',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='booking_table',
            name='rooms',
            field=models.CharField(choices=[('Standard Room', 'Standard Room'), ('Double Standard Room', 'Double Standard Room'), ('Executive Room', 'Executive Room'), ('Deluxe Room', 'Deluxe Room'), ('Classic Suite', 'Classic Suite'), ('Presidential Suite', 'Presidential Suite')], max_length=60),
        ),
        migrations.AlterField(
            model_name='check_in_table',
            name='rooms',
            field=models.CharField(choices=[('Standard Room', 'Standard Room'), ('Double Standard Room', 'Double Standard Room'), ('Executive Room', 'Executive Room'), ('Deluxe Room', 'Deluxe Room'), ('Classic Suite', 'Classic Suite'), ('Presidential Suite', 'Presidential Suite')], max_length=60),
        ),
        migrations.AlterField(
            model_name='check_out_table',
            name='rooms',
            field=models.CharField(choices=[('Standard Room', 'Standard Room'), ('Double Standard Room', 'Double Standard Room'), ('Executive Room', 'Executive Room'), ('Deluxe Room', 'Deluxe Room'), ('Classic Suite', 'Classic Suite'), ('Presidential Suite', 'Presidential Suite')], max_length=60),
        ),
        migrations.AlterField(
            model_name='room_table',
            name='rooms',
            field=models.CharField(choices=[('Standard Room', 'Standard Room'), ('Double Standard Room', 'Double Standard Room'), ('Executive Room', 'Executive Room'), ('Deluxe Room', 'Deluxe Room'), ('Classic Suite', 'Classic Suite'), ('Presidential Suite', 'Presidential Suite')], max_length=50),
        ),
    ]
