# Generated by Django 4.0.5 on 2022-08-03 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookingapp', '0018_booking_table_room_price_booking_table_total_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_table',
            name='real_check_in',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='booking_table',
            name='real_check_out',
            field=models.DateTimeField(null=True),
        ),
    ]
